# Generated by Django 3.1.7 on 2021-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='pics')),
                ('image2', models.ImageField(upload_to='pics')),
                ('image3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleserved', models.IntegerField()),
                ('Childabusecases', models.IntegerField()),
                ('d2l', models.IntegerField()),
            ],
        ),
    ]
