# Generated by Django 3.1.7 on 2021-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=120)),
                ('img1', models.ImageField(upload_to='pics')),
                ('btn_text1', models.CharField(max_length=120)),
                ('btn_link1', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Image2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(default=True, max_length=120)),
                ('img2', models.ImageField(upload_to='pics')),
                ('btn_text2', models.CharField(max_length=120)),
                ('btn_link2', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Image3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title3', models.CharField(default=True, max_length=120)),
                ('img3', models.ImageField(upload_to='pics')),
                ('btn_text3', models.CharField(max_length=120)),
                ('btn_link3', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Slideshow',
        ),
    ]
