# Generated by Django 3.1.7 on 2021-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_statisticscannon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default=True, max_length=120)),
                ('name', models.CharField(default=True, max_length=120)),
                ('child_image', models.ImageField(upload_to='pics')),
                ('older_image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
