# Generated by Django 3.1.7 on 2021-03-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_boardmember_executivecommittee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivecommittee',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='title',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
