# Generated by Django 3.1.7 on 2021-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.IntegerField(default=False),
        ),
    ]
