# Generated by Django 3.1.7 on 2021-03-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_team_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
