# Generated by Django 3.1.7 on 2021-03-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_rutherfordservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutherfordService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='RutherfordServices',
        ),
    ]
