# Generated by Django 3.1.7 on 2021-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210402_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cannonservice',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rutherfordservice',
            name='description',
            field=models.TextField(),
        ),
    ]
