# Generated by Django 3.1.7 on 2021-04-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_team_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='position_to_right',
        ),
        migrations.AddField(
            model_name='event',
            name='event_register',
            field=models.URLField(default=False),
        ),
    ]
