# Generated by Django 3.1.7 on 2021-04-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20210405_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='description',
            field=models.URLField(default='None'),
        ),
    ]
