# Generated by Django 3.1.7 on 2021-04-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20210405_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarknesstoLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=120)),
                ('page_description', models.TextField(max_length=1000)),
                ('image_title', models.CharField(max_length=120)),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
            ],
        ),
    ]
