# Generated by Django 3.1.7 on 2021-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20210413_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image2',
        ),
        migrations.DeleteModel(
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='image1',
            name='img1',
        ),
        migrations.AddField(
            model_name='image1',
            name='carousel_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='darknesstolight',
            name='description',
            field=models.TextField(default='Add description'),
        ),
        migrations.AlterField(
            model_name='darknesstolight',
            name='title',
            field=models.CharField(default='Add Title', max_length=120),
        ),
    ]
