# Generated by Django 3.1.7 on 2021-04-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20210415_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image1',
            new_name='SlideshowImages',
        ),
        migrations.RenameField(
            model_name='slideshowimages',
            old_name='btn_link1',
            new_name='btn_link',
        ),
        migrations.RenameField(
            model_name='slideshowimages',
            old_name='btn_text1',
            new_name='btn_text',
        ),
    ]
