# Generated by Django 3.1.7 on 2021-04-21 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20210415_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='GratitudeCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(default='default.jpg', upload_to='pics')),
                ('title', models.CharField(default='Add title', max_length=120)),
                ('description', models.TextField(default='Add description')),
                ('sponsorsText', models.TextField(default='Add Sponsors')),
                ('buttonID', models.CharField(default='Add an ID', max_length=60)),
            ],
        ),
        migrations.AlterModelOptions(
            name='executivecommittee',
            options={'verbose_name_plural': 'Directors'},
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='default.jpg', upload_to='pics')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.gratitudecards')),
            ],
        ),
    ]
